version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # This is the recommended Node.js version for Amplify Gen 2
    commands:
      # Install the Amplify Gen 2 CLI (now named ampx) globally
      - npm install -g @aws-amplify/cli@latest
      # Ensure npm global bin is in PATH
      - export PATH=$(npm config get prefix)/bin:$PATH
      # Install your frontend project's dependencies
      - npm ci

  pre_build:
    commands:
      # Use the correct Gen 2 command: ampx pull
      - ampx pull --appId d3n39g6wi0n3qw --envName $AMPLIFY_ENV_NAME --yes
      # ... rest of your pre_build commands if any (e.g., cp amplify_outputs.json)

  build:
    commands:
      - npm run build

  post_build:
    commands:
      # ... (your S3 sync commands)
artifacts:
  files:
    - '**/*'
  baseDirectory: dist