version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Or your specific Node.js version
    commands:
      - npm ci # Install your frontend project's dependencies
      # You *might* still need the global install for other reasons,
      # but for `amplify pull` specifically, npx can often find it.
      # If you're confident `npx` will resolve it, you could even remove the global install here
      - npm install -g @aws-amplify/cli@latest # Keep this for robustness

  pre_build:
    commands:
      # Call amplify using npx
      - npx amplify pull --appId d3n39g6wi0n3qw --envName $AMPLIFY_ENV_NAME --yes
      # ... rest of your pre_build commands

  build:
    commands:
      - npm run build

  post_build:
    commands:
      # ... (your S3 sync commands)
artifacts:
  files:
    - '**/*'
  baseDirectory: dist