version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @aws-amplify/cli
      - npm install

  pre_build:
    commands:
      - echo "Pulling Amplify environment"
      - amplify pull \
          --appId d3n39g6wi0n3qw \
          --envName prod \
          --region us-east-1 \
          --yes \
          --amplify '{"envName":"prod"}' \
          --providers '{"awscloudformation":{"configLevel":"project","useProfile":false,"accessKeyId":"'$AWS_ACCESS_KEY_ID'","secretAccessKey":"'$AWS_SECRET_ACCESS_KEY'","region":"us-east-1"}}' \
          --categories '{}'

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  baseDirectory: dist # Your Vue build output directory (e.g., 'dist' for Vite)